# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10af4efc719bac32a429d2f15b4c8479609b757d6ac2f5b18031eb50a33627caf919fd7e08b54c6227245bc96ba966864444c454292aea7359599040e9cf2254

  better_doctor_api_key: <%= ENV['BETTER_DOCTOR_API_KEY'] %>
  yelp_api_key: <%= ENV['YELP_API_KEY'] %>

test:
  secret_key_base: 0d332e240ffdb27ae221c1ab3d97e3d4b2474f944f4b733e59f193fd9a38ffb3d4cfcf961fdf7543e8299f0376d653cb767f20a0294f3a9b7ea091b0097c567b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
